// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nobetci.Web.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nobetci.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260111173107_AddSeoContentPages")]
    partial class AddSeoContentPages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("tr");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PremiumExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.ContentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CtaText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CtaUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PageType")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PageType");

                    b.HasIndex("Slug", "Language")
                        .IsUnique();

                    b.ToTable("ContentPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "<div class='feature-content'>\r\n<h2>Nöbet Listesi Nedir?</h2>\r\n<p>Nöbet listesi, bir kurumdaki personelin hangi gün ve saatlerde çalışacağını gösteren planlama aracıdır. Hastaneler, fabrikalar, güvenlik şirketleri ve 7/24 hizmet veren tüm işletmeler için vazgeçilmezdir.</p>\r\n\r\n<h2>Geldimmi ile Nöbet Listesi Oluşturma</h2>\r\n<p>Geldimmi, nöbet listesi oluşturmayı son derece kolay hale getirir:</p>\r\n<ul>\r\n    <li><strong>Hızlı Personel Ekleme:</strong> Excel'den kopyala-yapıştır ile anında personel ekleyin</li>\r\n    <li><strong>Esnek Vardiya Şablonları:</strong> Sabah, akşam, gece veya özel vardiyalar tanımlayın</li>\r\n    <li><strong>Sürükle-Bırak Atama:</strong> Takvim üzerinde kolayca nöbet atayın</li>\r\n    <li><strong>Akıllı Dağıtım:</strong> Algoritmamız nöbetleri adil şekilde dağıtır</li>\r\n</ul>\r\n\r\n<h2>Özellikler</h2>\r\n<h3>📅 Aylık Takvim Görünümü</h3>\r\n<p>Tüm ayı tek bakışta görün. Kimin ne zaman çalıştığını anında takip edin.</p>\r\n\r\n<h3>🎨 Renk Kodlama</h3>\r\n<p>Farklı vardiya türlerini renklerle ayırt edin. Sabah mavisi, gece moru gibi.</p>\r\n\r\n<h3>📱 Mobil Uyumlu</h3>\r\n<p>Telefonunuzdan veya tabletinizden nöbet listesi oluşturun ve paylaşın.</p>\r\n\r\n<h3>📥 Excel Export</h3>\r\n<p>Oluşturduğunuz nöbet listesini tek tıkla Excel'e aktarın.</p>\r\n\r\n<h2>Kimler İçin?</h2>\r\n<ul>\r\n    <li>Hastane ve sağlık kuruluşları</li>\r\n    <li>Fabrika ve üretim tesisleri</li>\r\n    <li>Güvenlik şirketleri</li>\r\n    <li>Çağrı merkezleri</li>\r\n    <li>Otel ve turizm işletmeleri</li>\r\n    <li>Market ve perakende zincirleri</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Hemen Ücretsiz Başla",
                            CtaUrl = "/app",
                            DisplayOrder = 1,
                            IsPublished = true,
                            Language = "tr",
                            MetaDescription = "Ücretsiz online nöbet listesi oluşturun. Hastane, fabrika, güvenlik ve tüm sektörler için akıllı nöbet planlama sistemi. Kayıt olmadan hemen başlayın.",
                            MetaKeywords = "nöbet listesi, nöbet programı, vardiya planlama, nöbet çizelgesi, online nöbet, ücretsiz nöbet programı",
                            PageType = 1,
                            Slug = "nobet-listesi-olusturma",
                            Subtitle = "Saniyeler içinde profesyonel nöbet listeleri oluşturun",
                            Title = "Online Nöbet Listesi Oluşturma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Content = "<div class='feature-content'>\r\n<h2>Hemşireler İçin Özel Çözüm</h2>\r\n<p>Hemşire nöbet planlaması, sağlık sektörünün en zorlu konularından biridir. Geldimmi, hemşirelerin iş yükünü dengelemek ve adil bir çalışma ortamı sağlamak için özel olarak tasarlanmıştır.</p>\r\n\r\n<h2>Hemşire Nöbet Planlamasının Zorlukları</h2>\r\n<ul>\r\n    <li>Gece nöbetlerinin adil dağıtılması</li>\r\n    <li>Hafta sonu çalışmalarının dengelenmesi</li>\r\n    <li>Ardışık nöbet kontrolü</li>\r\n    <li>Yasal dinlenme sürelerine uyum</li>\r\n    <li>Acil durum ve izin yönetimi</li>\r\n</ul>\r\n\r\n<h2>Geldimmi Nasıl Yardımcı Olur?</h2>\r\n<h3>⚖️ Adil Dağıtım Algoritması</h3>\r\n<p>Akıllı algoritmamız, gece nöbetlerini ve hafta sonu çalışmalarını tüm hemşireler arasında eşit dağıtır.</p>\r\n\r\n<h3>🌙 Gece Nöbeti Takibi</h3>\r\n<p>Her hemşirenin kaç gece nöbeti tuttuğunu otomatik hesaplar ve puantaja yansıtır.</p>\r\n\r\n<h3>📊 Detaylı Puantaj</h3>\r\n<p>Normal çalışma, gece çalışması, hafta sonu ve fazla mesai saatlerini ayrı ayrı hesaplar.</p>\r\n\r\n<h3>🔄 16 Saatlik Nöbet Desteği</h3>\r\n<p>Hemşire nöbetlerinde sık kullanılan 16:00-08:00 gibi ertesi güne sarkan vardiyaları destekler.</p>\r\n\r\n<h2>Örnek Hemşire Nöbet Planı</h2>\r\n<p>10 hemşireli bir serviste, sistemimiz otomatik olarak:</p>\r\n<ul>\r\n    <li>Her hemşireye ayda ortalama 4-5 gece nöbeti atar</li>\r\n    <li>Hafta sonu çalışmalarını dengeler</li>\r\n    <li>Ardışık gece nöbeti oluşmasını engeller</li>\r\n    <li>İzin ve raporları dikkate alır</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Ücretsiz Dene",
                            CtaUrl = "/app",
                            DisplayOrder = 2,
                            IsPublished = true,
                            Language = "tr",
                            MetaDescription = "Hastaneler için özel hemşire nöbet planlama sistemi. Adil dağıtım algoritması, gece nöbeti takibi ve otomatik puantaj. Ücretsiz deneyin.",
                            MetaKeywords = "hemşire nöbet programı, hastane nöbet listesi, hemşire vardiya, sağlık personeli nöbet, hemşire çalışma saatleri",
                            PageType = 1,
                            Slug = "hemsire-nobet-programi",
                            Subtitle = "Hastaneler için özel tasarlanmış akıllı nöbet sistemi",
                            Title = "Hemşire Nöbet Programı",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Content = "<div class='feature-content'>\r\n<h2>Nöbet Dağıtımında Adalet Neden Önemli?</h2>\r\n<p>Adaletsiz nöbet dağıtımı, çalışan memnuniyetsizliği, motivasyon kaybı ve hatta işten ayrılmalara neden olabilir. Geldimmi'nin akıllı algoritması bu sorunu çözer.</p>\r\n\r\n<h2>Adil Dağıtım Kriterleri</h2>\r\n<ul>\r\n    <li><strong>Gece Nöbetleri:</strong> Her çalışana eşit sayıda gece nöbeti</li>\r\n    <li><strong>Hafta Sonu:</strong> Cumartesi ve Pazar çalışmalarının dengeli dağıtımı</li>\r\n    <li><strong>Resmi Tatiller:</strong> Bayram ve tatil günlerinin adil paylaşımı</li>\r\n    <li><strong>Toplam Çalışma Saati:</strong> Aylık çalışma sürelerinin dengelenmesi</li>\r\n</ul>\r\n\r\n<h2>Algoritmamız Nasıl Çalışır?</h2>\r\n<h3>1. Veri Toplama</h3>\r\n<p>Geçmiş nöbet verilerini ve çalışan tercihlerini analiz eder.</p>\r\n\r\n<h3>2. Kısıtları Belirleme</h3>\r\n<p>İzinler, raporlar ve yasal dinlenme süreleri hesaba katılır.</p>\r\n\r\n<h3>3. Optimizasyon</h3>\r\n<p>En adil dağıtımı bulmak için matematiksel optimizasyon uygulanır.</p>\r\n\r\n<h3>4. Dengeleme</h3>\r\n<p>Gece, hafta sonu ve tatil nöbetleri tüm personel arasında eşitlenir.</p>\r\n\r\n<h2>Sonuçlar</h2>\r\n<ul>\r\n    <li>✅ %95 daha az nöbet şikayeti</li>\r\n    <li>✅ Çalışan memnuniyetinde artış</li>\r\n    <li>✅ Yönetici iş yükünde azalma</li>\r\n    <li>✅ Şeffaf ve ölçülebilir dağıtım</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Şimdi Dene",
                            CtaUrl = "/app",
                            DisplayOrder = 3,
                            IsPublished = true,
                            Language = "tr",
                            MetaDescription = "Akıllı algoritma ile adil nöbet dağıtımı. Gece, hafta sonu ve tatil nöbetlerini dengeli şekilde planlayın. Çalışan memnuniyetini artırın.",
                            MetaKeywords = "adil nöbet dağıtımı, nöbet algoritması, dengeli vardiya, eşit nöbet, nöbet adaleti",
                            PageType = 1,
                            Slug = "adil-nobet-dagitimi",
                            Subtitle = "Akıllı algoritma ile dengeli ve adil nöbet planlaması",
                            Title = "Adil Nöbet Dağıtım Sistemi",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Content = "<div class='feature-content'>\r\n<h2>Puantaj Nedir?</h2>\r\n<p>Puantaj, personelin aylık çalışma saatlerini ve türlerini gösteren dokümandır. Bordro hesaplamasının temelini oluşturur ve yasal bir zorunluluktur.</p>\r\n\r\n<h2>Geldimmi ile Otomatik Puantaj</h2>\r\n<p>Nöbet listesi oluşturduktan sonra, tek tıkla detaylı puantaj raporunuzu alın:</p>\r\n\r\n<h3>📊 Hesaplanan Değerler</h3>\r\n<ul>\r\n    <li><strong>Normal Çalışma:</strong> Standart mesai saatleri içindeki çalışma</li>\r\n    <li><strong>Gece Çalışması:</strong> 20:00-06:00 arası çalışma saatleri</li>\r\n    <li><strong>Hafta Sonu:</strong> Cumartesi ve Pazar günleri çalışma</li>\r\n    <li><strong>Resmi Tatil:</strong> Bayram ve resmi tatil günleri çalışma</li>\r\n    <li><strong>Fazla Mesai:</strong> Günlük veya aylık limite göre hesaplanan ek çalışma</li>\r\n</ul>\r\n\r\n<h3>⚙️ Hesaplama Modları</h3>\r\n<p><strong>Günlük Mod:</strong> Her gün için ayrı fazla mesai hesabı. Örneğin, günlük 8 saat çalışması gereken biri 10 saat çalıştıysa, o gün 2 saat fazla mesai yazılır.</p>\r\n<p><strong>Aylık Mod:</strong> Ay sonunda toplam çalışma saatine bakılır. Aylık hedef 176 saat, toplam çalışma 180 saat ise, 4 saat fazla mesai hesaplanır.</p>\r\n\r\n<h3>🔧 Ayarlanabilir Parametreler</h3>\r\n<ul>\r\n    <li>Gece başlangıç/bitiş saatleri (örn: 20:00-06:00)</li>\r\n    <li>Günlük çalışma hedefi (örn: 8 saat)</li>\r\n    <li>Aylık çalışma hedefi (örn: 176 saat)</li>\r\n    <li>Mola süreleri</li>\r\n</ul>\r\n\r\n<h2>Excel Export</h2>\r\n<p>Oluşturulan puantajı tek tıkla Excel'e aktarın. Bordro sistemlerinize kolayca entegre edin.</p>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Puantaj Oluştur",
                            CtaUrl = "/app",
                            DisplayOrder = 4,
                            IsPublished = true,
                            Language = "tr",
                            MetaDescription = "Nöbet listesinden otomatik puantaj oluşturun. Fazla mesai, gece çalışması, hafta sonu ve tatil saatlerini ayrı ayrı hesaplayın. Excel export.",
                            MetaKeywords = "puantaj hesaplama, puantaj oluşturma, mesai hesabı, çalışma saati hesaplama, otomatik puantaj",
                            PageType = 1,
                            Slug = "puantaj-hesaplama",
                            Subtitle = "Nöbet listesinden otomatik puantaj ve mesai hesabı",
                            Title = "Online Puantaj Hesaplama",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Content = "<div class='feature-content'>\r\n<h2>Fazla Mesai Nedir?</h2>\r\n<p>Fazla mesai (overtime), çalışanın yasal veya sözleşmesel çalışma süresini aşan çalışmasıdır. Türkiye'de İş Kanunu'na göre haftalık 45 saati aşan çalışmalar fazla mesai sayılır.</p>\r\n\r\n<h2>İki Farklı Hesaplama Modu</h2>\r\n<h3>📅 Günlük Hesaplama</h3>\r\n<p>Her gün için ayrı ayrı fazla mesai hesaplanır:</p>\r\n<ul>\r\n    <li>Günlük çalışma hedefi: 8 saat</li>\r\n    <li>Bugün çalışılan: 11 saat</li>\r\n    <li>Fazla mesai: 3 saat</li>\r\n</ul>\r\n<p><em>Avantajı: Her günün fazla mesaisi net görülür</em></p>\r\n\r\n<h3>📆 Aylık Hesaplama</h3>\r\n<p>Ay sonunda toplam saat üzerinden hesaplanır:</p>\r\n<ul>\r\n    <li>Aylık çalışma hedefi: 176 saat</li>\r\n    <li>Toplam çalışılan: 184 saat</li>\r\n    <li>Fazla mesai: 8 saat</li>\r\n</ul>\r\n<p><em>Avantajı: Bazı günler fazla, bazı günler eksik çalışma dengelenir</em></p>\r\n\r\n<h2>Gece Çalışması ve Fazla Mesai</h2>\r\n<p>Örnek: Bir hemşire 16:00-08:00 (16 saat) nöbet tutmuş.</p>\r\n<ul>\r\n    <li>Normal çalışma hedefi: 8 saat/gün × 2 gün = 16 saat</li>\r\n    <li>Çalışılan: 16 saat</li>\r\n    <li>Fazla mesai: 0 saat</li>\r\n    <li>Gece çalışması (20:00-06:00): 10 saat</li>\r\n</ul>\r\n<p>Bu durumda fazla mesai yoktur, ancak 10 saat gece çalışması tazminatı uygulanabilir.</p>\r\n\r\n<h2>Yasal Sınırlar</h2>\r\n<ul>\r\n    <li>Günlük fazla mesai: Maksimum 3 saat</li>\r\n    <li>Yıllık fazla mesai: Maksimum 270 saat</li>\r\n    <li>Fazla mesai ücreti: Normal ücretin %50 fazlası</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Hesaplamaya Başla",
                            CtaUrl = "/app",
                            DisplayOrder = 5,
                            IsPublished = true,
                            Language = "tr",
                            MetaDescription = "Günlük ve aylık fazla mesai hesaplama. Otomatik overtime takibi, yasal sınırlar ve raporlama. İş Kanunu'na uygun hesaplama.",
                            MetaKeywords = "fazla mesai hesaplama, overtime hesabı, ek mesai, mesai ücreti, fazla çalışma",
                            PageType = 1,
                            Slug = "fazla-mesai-hesaplama",
                            Subtitle = "Günlük veya aylık modda otomatik fazla mesai hesabı",
                            Title = "Fazla Mesai Hesaplama Sistemi",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Content = "<div class='feature-content'>\r\n<h2>What is Shift Scheduling?</h2>\r\n<p>Shift scheduling is the process of creating work schedules that assign employees to specific shifts. It's essential for hospitals, factories, security companies, and any business operating 24/7.</p>\r\n\r\n<h2>Shift Scheduling with Geldimmi</h2>\r\n<p>Geldimmi makes shift scheduling incredibly easy:</p>\r\n<ul>\r\n    <li><strong>Quick Employee Import:</strong> Copy-paste from Excel to add employees instantly</li>\r\n    <li><strong>Flexible Shift Templates:</strong> Define morning, evening, night, or custom shifts</li>\r\n    <li><strong>Drag-and-Drop Assignment:</strong> Easily assign shifts on the calendar</li>\r\n    <li><strong>Smart Distribution:</strong> Our algorithm distributes shifts fairly</li>\r\n</ul>\r\n\r\n<h2>Features</h2>\r\n<h3>📅 Monthly Calendar View</h3>\r\n<p>See the entire month at a glance. Track who's working when instantly.</p>\r\n\r\n<h3>🎨 Color Coding</h3>\r\n<p>Distinguish different shift types with colors. Morning blue, night purple, etc.</p>\r\n\r\n<h3>📱 Mobile Friendly</h3>\r\n<p>Create and share shift schedules from your phone or tablet.</p>\r\n\r\n<h3>📥 Excel Export</h3>\r\n<p>Export your shift schedule to Excel with one click.</p>\r\n\r\n<h2>Who Is It For?</h2>\r\n<ul>\r\n    <li>Hospitals and healthcare facilities</li>\r\n    <li>Factories and manufacturing plants</li>\r\n    <li>Security companies</li>\r\n    <li>Call centers</li>\r\n    <li>Hotels and tourism businesses</li>\r\n    <li>Retail stores and chains</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Start Free Now",
                            CtaUrl = "/app",
                            DisplayOrder = 1,
                            IsPublished = true,
                            Language = "en",
                            MetaDescription = "Free online shift scheduling tool. Create employee schedules for hospitals, factories, and businesses. Smart algorithm for fair distribution. Start without registration.",
                            MetaKeywords = "shift scheduling, employee scheduling, work schedule maker, duty roster, shift planner, free scheduling software",
                            PageType = 1,
                            Slug = "shift-scheduling",
                            Subtitle = "Create professional shift schedules in seconds",
                            Title = "Online Shift Scheduling Software",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Content = "<div class='feature-content'>\r\n<h2>A Solution Built for Nurses</h2>\r\n<p>Nurse shift planning is one of the most challenging aspects of healthcare management. Geldimmi is specifically designed to balance nurse workloads and create a fair working environment.</p>\r\n\r\n<h2>Challenges in Nurse Scheduling</h2>\r\n<ul>\r\n    <li>Fair distribution of night shifts</li>\r\n    <li>Balancing weekend work</li>\r\n    <li>Preventing consecutive night shifts</li>\r\n    <li>Compliance with legal rest periods</li>\r\n    <li>Emergency and leave management</li>\r\n</ul>\r\n\r\n<h2>How Geldimmi Helps</h2>\r\n<h3>⚖️ Fair Distribution Algorithm</h3>\r\n<p>Our smart algorithm distributes night shifts and weekend work equally among all nurses.</p>\r\n\r\n<h3>🌙 Night Shift Tracking</h3>\r\n<p>Automatically calculates how many night shifts each nurse has worked and reflects it in the timesheet.</p>\r\n\r\n<h3>📊 Detailed Timesheet</h3>\r\n<p>Calculates regular work, night work, weekends, and overtime separately.</p>\r\n\r\n<h3>🔄 16-Hour Shift Support</h3>\r\n<p>Supports overnight shifts like 4 PM to 8 AM commonly used in nursing.</p>\r\n\r\n<h2>Example Nurse Schedule</h2>\r\n<p>In a ward with 10 nurses, our system automatically:</p>\r\n<ul>\r\n    <li>Assigns each nurse an average of 4-5 night shifts per month</li>\r\n    <li>Balances weekend work</li>\r\n    <li>Prevents consecutive night shifts</li>\r\n    <li>Considers leaves and sick days</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Try Free",
                            CtaUrl = "/app",
                            DisplayOrder = 2,
                            IsPublished = true,
                            Language = "en",
                            MetaDescription = "Specialized nurse scheduling software for hospitals. Fair distribution algorithm, night shift tracking, and automatic timesheet. Try free.",
                            MetaKeywords = "nurse shift planner, hospital scheduling, nurse roster, healthcare scheduling, nurse duty schedule, nursing shifts",
                            PageType = 1,
                            Slug = "nurse-shift-planner",
                            Subtitle = "Smart scheduling system designed for hospitals",
                            Title = "Nurse Shift Planner",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Content = "<div class='feature-content'>\r\n<h2>Why Is Fairness Important in Shift Distribution?</h2>\r\n<p>Unfair shift distribution can lead to employee dissatisfaction, motivation loss, and even resignations. Geldimmi's smart algorithm solves this problem.</p>\r\n\r\n<h2>Fair Distribution Criteria</h2>\r\n<ul>\r\n    <li><strong>Night Shifts:</strong> Equal number of night shifts for each employee</li>\r\n    <li><strong>Weekends:</strong> Balanced distribution of Saturday and Sunday work</li>\r\n    <li><strong>Holidays:</strong> Fair sharing of public holiday duties</li>\r\n    <li><strong>Total Hours:</strong> Balancing monthly work hours</li>\r\n</ul>\r\n\r\n<h2>How Our Algorithm Works</h2>\r\n<h3>1. Data Collection</h3>\r\n<p>Analyzes past shift data and employee preferences.</p>\r\n\r\n<h3>2. Constraint Definition</h3>\r\n<p>Considers leaves, sick days, and legal rest periods.</p>\r\n\r\n<h3>3. Optimization</h3>\r\n<p>Mathematical optimization is applied to find the fairest distribution.</p>\r\n\r\n<h3>4. Balancing</h3>\r\n<p>Night, weekend, and holiday shifts are equalized among all staff.</p>\r\n\r\n<h2>Results</h2>\r\n<ul>\r\n    <li>✅ 95% fewer shift complaints</li>\r\n    <li>✅ Increased employee satisfaction</li>\r\n    <li>✅ Reduced manager workload</li>\r\n    <li>✅ Transparent and measurable distribution</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Try Now",
                            CtaUrl = "/app",
                            DisplayOrder = 3,
                            IsPublished = true,
                            Language = "en",
                            MetaDescription = "Smart algorithm for fair shift distribution. Balance night, weekend, and holiday shifts. Increase employee satisfaction.",
                            MetaKeywords = "fair shift distribution, shift algorithm, balanced scheduling, equal shifts, shift fairness",
                            PageType = 1,
                            Slug = "fair-shift-distribution",
                            Subtitle = "Balanced and fair scheduling with smart algorithm",
                            Title = "Fair Shift Distribution System",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Content = "<div class='feature-content'>\r\n<h2>What is a Timesheet?</h2>\r\n<p>A timesheet is a document that shows the monthly working hours and types for each employee. It forms the basis of payroll calculation and is a legal requirement.</p>\r\n\r\n<h2>Automatic Timesheet with Geldimmi</h2>\r\n<p>After creating a shift schedule, get your detailed timesheet report with one click:</p>\r\n\r\n<h3>📊 Calculated Values</h3>\r\n<ul>\r\n    <li><strong>Regular Work:</strong> Work within standard working hours</li>\r\n    <li><strong>Night Work:</strong> Working hours between 8 PM and 6 AM</li>\r\n    <li><strong>Weekend:</strong> Saturday and Sunday work</li>\r\n    <li><strong>Public Holiday:</strong> Work on public holidays</li>\r\n    <li><strong>Overtime:</strong> Extra work calculated daily or monthly</li>\r\n</ul>\r\n\r\n<h3>⚙️ Calculation Modes</h3>\r\n<p><strong>Daily Mode:</strong> Overtime calculated separately for each day. For example, if someone who should work 8 hours works 10 hours, 2 hours overtime is recorded for that day.</p>\r\n<p><strong>Monthly Mode:</strong> Based on total hours at month end. If monthly target is 176 hours and total work is 180 hours, 4 hours overtime is calculated.</p>\r\n\r\n<h3>🔧 Adjustable Parameters</h3>\r\n<ul>\r\n    <li>Night start/end times (e.g., 8 PM - 6 AM)</li>\r\n    <li>Daily work target (e.g., 8 hours)</li>\r\n    <li>Monthly work target (e.g., 176 hours)</li>\r\n    <li>Break times</li>\r\n</ul>\r\n\r\n<h2>Excel Export</h2>\r\n<p>Export the generated timesheet to Excel with one click. Easily integrate with your payroll systems.</p>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Create Timesheet",
                            CtaUrl = "/app",
                            DisplayOrder = 4,
                            IsPublished = true,
                            Language = "en",
                            MetaDescription = "Generate automatic timesheets from shift schedules. Calculate overtime, night work, weekends, and holidays separately. Excel export.",
                            MetaKeywords = "timesheet calculation, timesheet generator, hours calculation, work hours tracking, automatic timesheet",
                            PageType = 1,
                            Slug = "timesheet-calculation",
                            Subtitle = "Automatic timesheet and work hours calculation from shift schedules",
                            Title = "Online Timesheet Calculation",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Content = "<div class='feature-content'>\r\n<h2>What is Overtime?</h2>\r\n<p>Overtime is work that exceeds an employee's legal or contractual working hours. In most countries, work exceeding 40-45 hours per week is considered overtime.</p>\r\n\r\n<h2>Two Different Calculation Modes</h2>\r\n<h3>📅 Daily Calculation</h3>\r\n<p>Overtime is calculated separately for each day:</p>\r\n<ul>\r\n    <li>Daily work target: 8 hours</li>\r\n    <li>Worked today: 11 hours</li>\r\n    <li>Overtime: 3 hours</li>\r\n</ul>\r\n<p><em>Advantage: Each day's overtime is clearly visible</em></p>\r\n\r\n<h3>📆 Monthly Calculation</h3>\r\n<p>Calculated based on total hours at month end:</p>\r\n<ul>\r\n    <li>Monthly work target: 176 hours</li>\r\n    <li>Total worked: 184 hours</li>\r\n    <li>Overtime: 8 hours</li>\r\n</ul>\r\n<p><em>Advantage: Extra work on some days can be balanced by less work on others</em></p>\r\n\r\n<h2>Night Work and Overtime</h2>\r\n<p>Example: A nurse worked a 4 PM to 8 AM shift (16 hours).</p>\r\n<ul>\r\n    <li>Normal work target: 8 hours/day × 2 days = 16 hours</li>\r\n    <li>Worked: 16 hours</li>\r\n    <li>Overtime: 0 hours</li>\r\n    <li>Night work (8 PM - 6 AM): 10 hours</li>\r\n</ul>\r\n<p>In this case, there's no overtime, but 10 hours of night work premium may apply.</p>\r\n\r\n<h2>Legal Limits</h2>\r\n<ul>\r\n    <li>Daily overtime: Maximum 3 hours</li>\r\n    <li>Annual overtime: Maximum 270 hours</li>\r\n    <li>Overtime pay: 50% more than regular rate</li>\r\n</ul>\r\n</div>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CtaText = "Start Calculating",
                            CtaUrl = "/app",
                            DisplayOrder = 5,
                            IsPublished = true,
                            Language = "en",
                            MetaDescription = "Daily and monthly overtime calculation. Automatic overtime tracking, legal limits, and reporting. Labor law compliant calculation.",
                            MetaKeywords = "overtime calculation, overtime tracking, extra hours, overtime pay, work hours",
                            PageType = 1,
                            Slug = "overtime-calculation",
                            Subtitle = "Automatic overtime calculation in daily or monthly mode",
                            Title = "Overtime Calculation System",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DailyWorkHours")
                        .HasColumnType("numeric");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdentityNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeeklyWorkHours")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("OrganizationId", "IdentityNo");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.EmployeeAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("SpecificDate")
                        .HasColumnType("date");

                    b.Property<int>("TimePeriod")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAvailabilities");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HalfDayStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Date")
                        .IsUnique();

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyWorkHours")
                        .HasColumnType("numeric");

                    b.Property<string>("GuestSessionId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly>("NightEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("NightStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("OvertimeCalcMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("WeekendDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WeeklyWorkHours")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NightHours")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ShiftTemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("SpansNextDay")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ShiftTemplateId");

                    b.HasIndex("EmployeeId", "Date");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.ShiftTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<bool>("SpansNextDay")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsGlobal");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ShiftTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            EndTime = new TimeOnly(16, 0, 0),
                            IsActive = true,
                            IsGlobal = true,
                            Name = "Morning Shift",
                            NameKey = "shift.morning",
                            SpansNextDay = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            EndTime = new TimeOnly(0, 0, 0),
                            IsActive = true,
                            IsGlobal = true,
                            Name = "Evening Shift",
                            NameKey = "shift.evening",
                            SpansNextDay = false,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            EndTime = new TimeOnly(8, 0, 0),
                            IsActive = true,
                            IsGlobal = true,
                            Name = "Night Shift",
                            NameKey = "shift.night",
                            SpansNextDay = false,
                            StartTime = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            BreakMinutes = 60,
                            Color = "#22C55E",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            IsGlobal = true,
                            Name = "Full Day",
                            NameKey = "shift.fullday",
                            SpansNextDay = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            EndTime = new TimeOnly(8, 0, 0),
                            IsActive = true,
                            IsGlobal = true,
                            Name = "Nurse Duty (16h)",
                            NameKey = "shift.nurseduty",
                            SpansNextDay = true,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Color = "#DC2626",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            EndTime = new TimeOnly(8, 0, 0),
                            IsActive = true,
                            IsGlobal = true,
                            Name = "24h Duty",
                            NameKey = "shift.24h",
                            SpansNextDay = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nobetci.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Employee", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.Organization", "Organization")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nobetci.Web.Data.Entities.Unit", "Unit")
                        .WithMany("Employees")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.EmployeeAvailability", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.Employee", "Employee")
                        .WithMany("Availabilities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Holiday", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.Organization", "Organization")
                        .WithMany("Holidays")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Leave", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Organization", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.ApplicationUser", "User")
                        .WithMany("Organizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Shift", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nobetci.Web.Data.Entities.ShiftTemplate", "ShiftTemplate")
                        .WithMany()
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.ShiftTemplate", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.Organization", "Organization")
                        .WithMany("ShiftTemplates")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Unit", b =>
                {
                    b.HasOne("Nobetci.Web.Data.Entities.Organization", "Organization")
                        .WithMany("Units")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Employee", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Leaves");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Organization", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Holidays");

                    b.Navigation("ShiftTemplates");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Nobetci.Web.Data.Entities.Unit", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
