using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Nobetci.Web.Migrations
{
    /// <inheritdoc />
    public partial class AddSeoContentPages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "ContentPages",
                columns: new[] { "Id", "Content", "CreatedAt", "CtaText", "CtaUrl", "DisplayOrder", "IsPublished", "Language", "MetaDescription", "MetaKeywords", "PageType", "Slug", "Subtitle", "Title", "UpdatedAt" },
                values: new object[,]
                {
                    { 1, "<div class='feature-content'>\r\n<h2>Nöbet Listesi Nedir?</h2>\r\n<p>Nöbet listesi, bir kurumdaki personelin hangi gün ve saatlerde çalışacağını gösteren planlama aracıdır. Hastaneler, fabrikalar, güvenlik şirketleri ve 7/24 hizmet veren tüm işletmeler için vazgeçilmezdir.</p>\r\n\r\n<h2>Geldimmi ile Nöbet Listesi Oluşturma</h2>\r\n<p>Geldimmi, nöbet listesi oluşturmayı son derece kolay hale getirir:</p>\r\n<ul>\r\n    <li><strong>Hızlı Personel Ekleme:</strong> Excel'den kopyala-yapıştır ile anında personel ekleyin</li>\r\n    <li><strong>Esnek Vardiya Şablonları:</strong> Sabah, akşam, gece veya özel vardiyalar tanımlayın</li>\r\n    <li><strong>Sürükle-Bırak Atama:</strong> Takvim üzerinde kolayca nöbet atayın</li>\r\n    <li><strong>Akıllı Dağıtım:</strong> Algoritmamız nöbetleri adil şekilde dağıtır</li>\r\n</ul>\r\n\r\n<h2>Özellikler</h2>\r\n<h3>📅 Aylık Takvim Görünümü</h3>\r\n<p>Tüm ayı tek bakışta görün. Kimin ne zaman çalıştığını anında takip edin.</p>\r\n\r\n<h3>🎨 Renk Kodlama</h3>\r\n<p>Farklı vardiya türlerini renklerle ayırt edin. Sabah mavisi, gece moru gibi.</p>\r\n\r\n<h3>📱 Mobil Uyumlu</h3>\r\n<p>Telefonunuzdan veya tabletinizden nöbet listesi oluşturun ve paylaşın.</p>\r\n\r\n<h3>📥 Excel Export</h3>\r\n<p>Oluşturduğunuz nöbet listesini tek tıkla Excel'e aktarın.</p>\r\n\r\n<h2>Kimler İçin?</h2>\r\n<ul>\r\n    <li>Hastane ve sağlık kuruluşları</li>\r\n    <li>Fabrika ve üretim tesisleri</li>\r\n    <li>Güvenlik şirketleri</li>\r\n    <li>Çağrı merkezleri</li>\r\n    <li>Otel ve turizm işletmeleri</li>\r\n    <li>Market ve perakende zincirleri</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Hemen Ücretsiz Başla", "/app", 1, true, "tr", "Ücretsiz online nöbet listesi oluşturun. Hastane, fabrika, güvenlik ve tüm sektörler için akıllı nöbet planlama sistemi. Kayıt olmadan hemen başlayın.", "nöbet listesi, nöbet programı, vardiya planlama, nöbet çizelgesi, online nöbet, ücretsiz nöbet programı", 1, "nobet-listesi-olusturma", "Saniyeler içinde profesyonel nöbet listeleri oluşturun", "Online Nöbet Listesi Oluşturma", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 2, "<div class='feature-content'>\r\n<h2>Hemşireler İçin Özel Çözüm</h2>\r\n<p>Hemşire nöbet planlaması, sağlık sektörünün en zorlu konularından biridir. Geldimmi, hemşirelerin iş yükünü dengelemek ve adil bir çalışma ortamı sağlamak için özel olarak tasarlanmıştır.</p>\r\n\r\n<h2>Hemşire Nöbet Planlamasının Zorlukları</h2>\r\n<ul>\r\n    <li>Gece nöbetlerinin adil dağıtılması</li>\r\n    <li>Hafta sonu çalışmalarının dengelenmesi</li>\r\n    <li>Ardışık nöbet kontrolü</li>\r\n    <li>Yasal dinlenme sürelerine uyum</li>\r\n    <li>Acil durum ve izin yönetimi</li>\r\n</ul>\r\n\r\n<h2>Geldimmi Nasıl Yardımcı Olur?</h2>\r\n<h3>⚖️ Adil Dağıtım Algoritması</h3>\r\n<p>Akıllı algoritmamız, gece nöbetlerini ve hafta sonu çalışmalarını tüm hemşireler arasında eşit dağıtır.</p>\r\n\r\n<h3>🌙 Gece Nöbeti Takibi</h3>\r\n<p>Her hemşirenin kaç gece nöbeti tuttuğunu otomatik hesaplar ve puantaja yansıtır.</p>\r\n\r\n<h3>📊 Detaylı Puantaj</h3>\r\n<p>Normal çalışma, gece çalışması, hafta sonu ve fazla mesai saatlerini ayrı ayrı hesaplar.</p>\r\n\r\n<h3>🔄 16 Saatlik Nöbet Desteği</h3>\r\n<p>Hemşire nöbetlerinde sık kullanılan 16:00-08:00 gibi ertesi güne sarkan vardiyaları destekler.</p>\r\n\r\n<h2>Örnek Hemşire Nöbet Planı</h2>\r\n<p>10 hemşireli bir serviste, sistemimiz otomatik olarak:</p>\r\n<ul>\r\n    <li>Her hemşireye ayda ortalama 4-5 gece nöbeti atar</li>\r\n    <li>Hafta sonu çalışmalarını dengeler</li>\r\n    <li>Ardışık gece nöbeti oluşmasını engeller</li>\r\n    <li>İzin ve raporları dikkate alır</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Ücretsiz Dene", "/app", 2, true, "tr", "Hastaneler için özel hemşire nöbet planlama sistemi. Adil dağıtım algoritması, gece nöbeti takibi ve otomatik puantaj. Ücretsiz deneyin.", "hemşire nöbet programı, hastane nöbet listesi, hemşire vardiya, sağlık personeli nöbet, hemşire çalışma saatleri", 1, "hemsire-nobet-programi", "Hastaneler için özel tasarlanmış akıllı nöbet sistemi", "Hemşire Nöbet Programı", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 3, "<div class='feature-content'>\r\n<h2>Nöbet Dağıtımında Adalet Neden Önemli?</h2>\r\n<p>Adaletsiz nöbet dağıtımı, çalışan memnuniyetsizliği, motivasyon kaybı ve hatta işten ayrılmalara neden olabilir. Geldimmi'nin akıllı algoritması bu sorunu çözer.</p>\r\n\r\n<h2>Adil Dağıtım Kriterleri</h2>\r\n<ul>\r\n    <li><strong>Gece Nöbetleri:</strong> Her çalışana eşit sayıda gece nöbeti</li>\r\n    <li><strong>Hafta Sonu:</strong> Cumartesi ve Pazar çalışmalarının dengeli dağıtımı</li>\r\n    <li><strong>Resmi Tatiller:</strong> Bayram ve tatil günlerinin adil paylaşımı</li>\r\n    <li><strong>Toplam Çalışma Saati:</strong> Aylık çalışma sürelerinin dengelenmesi</li>\r\n</ul>\r\n\r\n<h2>Algoritmamız Nasıl Çalışır?</h2>\r\n<h3>1. Veri Toplama</h3>\r\n<p>Geçmiş nöbet verilerini ve çalışan tercihlerini analiz eder.</p>\r\n\r\n<h3>2. Kısıtları Belirleme</h3>\r\n<p>İzinler, raporlar ve yasal dinlenme süreleri hesaba katılır.</p>\r\n\r\n<h3>3. Optimizasyon</h3>\r\n<p>En adil dağıtımı bulmak için matematiksel optimizasyon uygulanır.</p>\r\n\r\n<h3>4. Dengeleme</h3>\r\n<p>Gece, hafta sonu ve tatil nöbetleri tüm personel arasında eşitlenir.</p>\r\n\r\n<h2>Sonuçlar</h2>\r\n<ul>\r\n    <li>✅ %95 daha az nöbet şikayeti</li>\r\n    <li>✅ Çalışan memnuniyetinde artış</li>\r\n    <li>✅ Yönetici iş yükünde azalma</li>\r\n    <li>✅ Şeffaf ve ölçülebilir dağıtım</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Şimdi Dene", "/app", 3, true, "tr", "Akıllı algoritma ile adil nöbet dağıtımı. Gece, hafta sonu ve tatil nöbetlerini dengeli şekilde planlayın. Çalışan memnuniyetini artırın.", "adil nöbet dağıtımı, nöbet algoritması, dengeli vardiya, eşit nöbet, nöbet adaleti", 1, "adil-nobet-dagitimi", "Akıllı algoritma ile dengeli ve adil nöbet planlaması", "Adil Nöbet Dağıtım Sistemi", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 4, "<div class='feature-content'>\r\n<h2>Puantaj Nedir?</h2>\r\n<p>Puantaj, personelin aylık çalışma saatlerini ve türlerini gösteren dokümandır. Bordro hesaplamasının temelini oluşturur ve yasal bir zorunluluktur.</p>\r\n\r\n<h2>Geldimmi ile Otomatik Puantaj</h2>\r\n<p>Nöbet listesi oluşturduktan sonra, tek tıkla detaylı puantaj raporunuzu alın:</p>\r\n\r\n<h3>📊 Hesaplanan Değerler</h3>\r\n<ul>\r\n    <li><strong>Normal Çalışma:</strong> Standart mesai saatleri içindeki çalışma</li>\r\n    <li><strong>Gece Çalışması:</strong> 20:00-06:00 arası çalışma saatleri</li>\r\n    <li><strong>Hafta Sonu:</strong> Cumartesi ve Pazar günleri çalışma</li>\r\n    <li><strong>Resmi Tatil:</strong> Bayram ve resmi tatil günleri çalışma</li>\r\n    <li><strong>Fazla Mesai:</strong> Günlük veya aylık limite göre hesaplanan ek çalışma</li>\r\n</ul>\r\n\r\n<h3>⚙️ Hesaplama Modları</h3>\r\n<p><strong>Günlük Mod:</strong> Her gün için ayrı fazla mesai hesabı. Örneğin, günlük 8 saat çalışması gereken biri 10 saat çalıştıysa, o gün 2 saat fazla mesai yazılır.</p>\r\n<p><strong>Aylık Mod:</strong> Ay sonunda toplam çalışma saatine bakılır. Aylık hedef 176 saat, toplam çalışma 180 saat ise, 4 saat fazla mesai hesaplanır.</p>\r\n\r\n<h3>🔧 Ayarlanabilir Parametreler</h3>\r\n<ul>\r\n    <li>Gece başlangıç/bitiş saatleri (örn: 20:00-06:00)</li>\r\n    <li>Günlük çalışma hedefi (örn: 8 saat)</li>\r\n    <li>Aylık çalışma hedefi (örn: 176 saat)</li>\r\n    <li>Mola süreleri</li>\r\n</ul>\r\n\r\n<h2>Excel Export</h2>\r\n<p>Oluşturulan puantajı tek tıkla Excel'e aktarın. Bordro sistemlerinize kolayca entegre edin.</p>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Puantaj Oluştur", "/app", 4, true, "tr", "Nöbet listesinden otomatik puantaj oluşturun. Fazla mesai, gece çalışması, hafta sonu ve tatil saatlerini ayrı ayrı hesaplayın. Excel export.", "puantaj hesaplama, puantaj oluşturma, mesai hesabı, çalışma saati hesaplama, otomatik puantaj", 1, "puantaj-hesaplama", "Nöbet listesinden otomatik puantaj ve mesai hesabı", "Online Puantaj Hesaplama", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 5, "<div class='feature-content'>\r\n<h2>Fazla Mesai Nedir?</h2>\r\n<p>Fazla mesai (overtime), çalışanın yasal veya sözleşmesel çalışma süresini aşan çalışmasıdır. Türkiye'de İş Kanunu'na göre haftalık 45 saati aşan çalışmalar fazla mesai sayılır.</p>\r\n\r\n<h2>İki Farklı Hesaplama Modu</h2>\r\n<h3>📅 Günlük Hesaplama</h3>\r\n<p>Her gün için ayrı ayrı fazla mesai hesaplanır:</p>\r\n<ul>\r\n    <li>Günlük çalışma hedefi: 8 saat</li>\r\n    <li>Bugün çalışılan: 11 saat</li>\r\n    <li>Fazla mesai: 3 saat</li>\r\n</ul>\r\n<p><em>Avantajı: Her günün fazla mesaisi net görülür</em></p>\r\n\r\n<h3>📆 Aylık Hesaplama</h3>\r\n<p>Ay sonunda toplam saat üzerinden hesaplanır:</p>\r\n<ul>\r\n    <li>Aylık çalışma hedefi: 176 saat</li>\r\n    <li>Toplam çalışılan: 184 saat</li>\r\n    <li>Fazla mesai: 8 saat</li>\r\n</ul>\r\n<p><em>Avantajı: Bazı günler fazla, bazı günler eksik çalışma dengelenir</em></p>\r\n\r\n<h2>Gece Çalışması ve Fazla Mesai</h2>\r\n<p>Örnek: Bir hemşire 16:00-08:00 (16 saat) nöbet tutmuş.</p>\r\n<ul>\r\n    <li>Normal çalışma hedefi: 8 saat/gün × 2 gün = 16 saat</li>\r\n    <li>Çalışılan: 16 saat</li>\r\n    <li>Fazla mesai: 0 saat</li>\r\n    <li>Gece çalışması (20:00-06:00): 10 saat</li>\r\n</ul>\r\n<p>Bu durumda fazla mesai yoktur, ancak 10 saat gece çalışması tazminatı uygulanabilir.</p>\r\n\r\n<h2>Yasal Sınırlar</h2>\r\n<ul>\r\n    <li>Günlük fazla mesai: Maksimum 3 saat</li>\r\n    <li>Yıllık fazla mesai: Maksimum 270 saat</li>\r\n    <li>Fazla mesai ücreti: Normal ücretin %50 fazlası</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Hesaplamaya Başla", "/app", 5, true, "tr", "Günlük ve aylık fazla mesai hesaplama. Otomatik overtime takibi, yasal sınırlar ve raporlama. İş Kanunu'na uygun hesaplama.", "fazla mesai hesaplama, overtime hesabı, ek mesai, mesai ücreti, fazla çalışma", 1, "fazla-mesai-hesaplama", "Günlük veya aylık modda otomatik fazla mesai hesabı", "Fazla Mesai Hesaplama Sistemi", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 6, "<div class='feature-content'>\r\n<h2>What is Shift Scheduling?</h2>\r\n<p>Shift scheduling is the process of creating work schedules that assign employees to specific shifts. It's essential for hospitals, factories, security companies, and any business operating 24/7.</p>\r\n\r\n<h2>Shift Scheduling with Geldimmi</h2>\r\n<p>Geldimmi makes shift scheduling incredibly easy:</p>\r\n<ul>\r\n    <li><strong>Quick Employee Import:</strong> Copy-paste from Excel to add employees instantly</li>\r\n    <li><strong>Flexible Shift Templates:</strong> Define morning, evening, night, or custom shifts</li>\r\n    <li><strong>Drag-and-Drop Assignment:</strong> Easily assign shifts on the calendar</li>\r\n    <li><strong>Smart Distribution:</strong> Our algorithm distributes shifts fairly</li>\r\n</ul>\r\n\r\n<h2>Features</h2>\r\n<h3>📅 Monthly Calendar View</h3>\r\n<p>See the entire month at a glance. Track who's working when instantly.</p>\r\n\r\n<h3>🎨 Color Coding</h3>\r\n<p>Distinguish different shift types with colors. Morning blue, night purple, etc.</p>\r\n\r\n<h3>📱 Mobile Friendly</h3>\r\n<p>Create and share shift schedules from your phone or tablet.</p>\r\n\r\n<h3>📥 Excel Export</h3>\r\n<p>Export your shift schedule to Excel with one click.</p>\r\n\r\n<h2>Who Is It For?</h2>\r\n<ul>\r\n    <li>Hospitals and healthcare facilities</li>\r\n    <li>Factories and manufacturing plants</li>\r\n    <li>Security companies</li>\r\n    <li>Call centers</li>\r\n    <li>Hotels and tourism businesses</li>\r\n    <li>Retail stores and chains</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Start Free Now", "/app", 1, true, "en", "Free online shift scheduling tool. Create employee schedules for hospitals, factories, and businesses. Smart algorithm for fair distribution. Start without registration.", "shift scheduling, employee scheduling, work schedule maker, duty roster, shift planner, free scheduling software", 1, "shift-scheduling", "Create professional shift schedules in seconds", "Online Shift Scheduling Software", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 7, "<div class='feature-content'>\r\n<h2>A Solution Built for Nurses</h2>\r\n<p>Nurse shift planning is one of the most challenging aspects of healthcare management. Geldimmi is specifically designed to balance nurse workloads and create a fair working environment.</p>\r\n\r\n<h2>Challenges in Nurse Scheduling</h2>\r\n<ul>\r\n    <li>Fair distribution of night shifts</li>\r\n    <li>Balancing weekend work</li>\r\n    <li>Preventing consecutive night shifts</li>\r\n    <li>Compliance with legal rest periods</li>\r\n    <li>Emergency and leave management</li>\r\n</ul>\r\n\r\n<h2>How Geldimmi Helps</h2>\r\n<h3>⚖️ Fair Distribution Algorithm</h3>\r\n<p>Our smart algorithm distributes night shifts and weekend work equally among all nurses.</p>\r\n\r\n<h3>🌙 Night Shift Tracking</h3>\r\n<p>Automatically calculates how many night shifts each nurse has worked and reflects it in the timesheet.</p>\r\n\r\n<h3>📊 Detailed Timesheet</h3>\r\n<p>Calculates regular work, night work, weekends, and overtime separately.</p>\r\n\r\n<h3>🔄 16-Hour Shift Support</h3>\r\n<p>Supports overnight shifts like 4 PM to 8 AM commonly used in nursing.</p>\r\n\r\n<h2>Example Nurse Schedule</h2>\r\n<p>In a ward with 10 nurses, our system automatically:</p>\r\n<ul>\r\n    <li>Assigns each nurse an average of 4-5 night shifts per month</li>\r\n    <li>Balances weekend work</li>\r\n    <li>Prevents consecutive night shifts</li>\r\n    <li>Considers leaves and sick days</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Try Free", "/app", 2, true, "en", "Specialized nurse scheduling software for hospitals. Fair distribution algorithm, night shift tracking, and automatic timesheet. Try free.", "nurse shift planner, hospital scheduling, nurse roster, healthcare scheduling, nurse duty schedule, nursing shifts", 1, "nurse-shift-planner", "Smart scheduling system designed for hospitals", "Nurse Shift Planner", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 8, "<div class='feature-content'>\r\n<h2>Why Is Fairness Important in Shift Distribution?</h2>\r\n<p>Unfair shift distribution can lead to employee dissatisfaction, motivation loss, and even resignations. Geldimmi's smart algorithm solves this problem.</p>\r\n\r\n<h2>Fair Distribution Criteria</h2>\r\n<ul>\r\n    <li><strong>Night Shifts:</strong> Equal number of night shifts for each employee</li>\r\n    <li><strong>Weekends:</strong> Balanced distribution of Saturday and Sunday work</li>\r\n    <li><strong>Holidays:</strong> Fair sharing of public holiday duties</li>\r\n    <li><strong>Total Hours:</strong> Balancing monthly work hours</li>\r\n</ul>\r\n\r\n<h2>How Our Algorithm Works</h2>\r\n<h3>1. Data Collection</h3>\r\n<p>Analyzes past shift data and employee preferences.</p>\r\n\r\n<h3>2. Constraint Definition</h3>\r\n<p>Considers leaves, sick days, and legal rest periods.</p>\r\n\r\n<h3>3. Optimization</h3>\r\n<p>Mathematical optimization is applied to find the fairest distribution.</p>\r\n\r\n<h3>4. Balancing</h3>\r\n<p>Night, weekend, and holiday shifts are equalized among all staff.</p>\r\n\r\n<h2>Results</h2>\r\n<ul>\r\n    <li>✅ 95% fewer shift complaints</li>\r\n    <li>✅ Increased employee satisfaction</li>\r\n    <li>✅ Reduced manager workload</li>\r\n    <li>✅ Transparent and measurable distribution</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Try Now", "/app", 3, true, "en", "Smart algorithm for fair shift distribution. Balance night, weekend, and holiday shifts. Increase employee satisfaction.", "fair shift distribution, shift algorithm, balanced scheduling, equal shifts, shift fairness", 1, "fair-shift-distribution", "Balanced and fair scheduling with smart algorithm", "Fair Shift Distribution System", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 9, "<div class='feature-content'>\r\n<h2>What is a Timesheet?</h2>\r\n<p>A timesheet is a document that shows the monthly working hours and types for each employee. It forms the basis of payroll calculation and is a legal requirement.</p>\r\n\r\n<h2>Automatic Timesheet with Geldimmi</h2>\r\n<p>After creating a shift schedule, get your detailed timesheet report with one click:</p>\r\n\r\n<h3>📊 Calculated Values</h3>\r\n<ul>\r\n    <li><strong>Regular Work:</strong> Work within standard working hours</li>\r\n    <li><strong>Night Work:</strong> Working hours between 8 PM and 6 AM</li>\r\n    <li><strong>Weekend:</strong> Saturday and Sunday work</li>\r\n    <li><strong>Public Holiday:</strong> Work on public holidays</li>\r\n    <li><strong>Overtime:</strong> Extra work calculated daily or monthly</li>\r\n</ul>\r\n\r\n<h3>⚙️ Calculation Modes</h3>\r\n<p><strong>Daily Mode:</strong> Overtime calculated separately for each day. For example, if someone who should work 8 hours works 10 hours, 2 hours overtime is recorded for that day.</p>\r\n<p><strong>Monthly Mode:</strong> Based on total hours at month end. If monthly target is 176 hours and total work is 180 hours, 4 hours overtime is calculated.</p>\r\n\r\n<h3>🔧 Adjustable Parameters</h3>\r\n<ul>\r\n    <li>Night start/end times (e.g., 8 PM - 6 AM)</li>\r\n    <li>Daily work target (e.g., 8 hours)</li>\r\n    <li>Monthly work target (e.g., 176 hours)</li>\r\n    <li>Break times</li>\r\n</ul>\r\n\r\n<h2>Excel Export</h2>\r\n<p>Export the generated timesheet to Excel with one click. Easily integrate with your payroll systems.</p>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Create Timesheet", "/app", 4, true, "en", "Generate automatic timesheets from shift schedules. Calculate overtime, night work, weekends, and holidays separately. Excel export.", "timesheet calculation, timesheet generator, hours calculation, work hours tracking, automatic timesheet", 1, "timesheet-calculation", "Automatic timesheet and work hours calculation from shift schedules", "Online Timesheet Calculation", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                    { 10, "<div class='feature-content'>\r\n<h2>What is Overtime?</h2>\r\n<p>Overtime is work that exceeds an employee's legal or contractual working hours. In most countries, work exceeding 40-45 hours per week is considered overtime.</p>\r\n\r\n<h2>Two Different Calculation Modes</h2>\r\n<h3>📅 Daily Calculation</h3>\r\n<p>Overtime is calculated separately for each day:</p>\r\n<ul>\r\n    <li>Daily work target: 8 hours</li>\r\n    <li>Worked today: 11 hours</li>\r\n    <li>Overtime: 3 hours</li>\r\n</ul>\r\n<p><em>Advantage: Each day's overtime is clearly visible</em></p>\r\n\r\n<h3>📆 Monthly Calculation</h3>\r\n<p>Calculated based on total hours at month end:</p>\r\n<ul>\r\n    <li>Monthly work target: 176 hours</li>\r\n    <li>Total worked: 184 hours</li>\r\n    <li>Overtime: 8 hours</li>\r\n</ul>\r\n<p><em>Advantage: Extra work on some days can be balanced by less work on others</em></p>\r\n\r\n<h2>Night Work and Overtime</h2>\r\n<p>Example: A nurse worked a 4 PM to 8 AM shift (16 hours).</p>\r\n<ul>\r\n    <li>Normal work target: 8 hours/day × 2 days = 16 hours</li>\r\n    <li>Worked: 16 hours</li>\r\n    <li>Overtime: 0 hours</li>\r\n    <li>Night work (8 PM - 6 AM): 10 hours</li>\r\n</ul>\r\n<p>In this case, there's no overtime, but 10 hours of night work premium may apply.</p>\r\n\r\n<h2>Legal Limits</h2>\r\n<ul>\r\n    <li>Daily overtime: Maximum 3 hours</li>\r\n    <li>Annual overtime: Maximum 270 hours</li>\r\n    <li>Overtime pay: 50% more than regular rate</li>\r\n</ul>\r\n</div>", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Start Calculating", "/app", 5, true, "en", "Daily and monthly overtime calculation. Automatic overtime tracking, legal limits, and reporting. Labor law compliant calculation.", "overtime calculation, overtime tracking, extra hours, overtime pay, work hours", 1, "overtime-calculation", "Automatic overtime calculation in daily or monthly mode", "Overtime Calculation System", new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 6);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 7);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 8);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 9);

            migrationBuilder.DeleteData(
                table: "ContentPages",
                keyColumn: "Id",
                keyValue: 10);
        }
    }
}
